"use client";

import { useState, useEffect, useCallback } from "react";
import { File, Download, RefreshCw, Loader2, FileText, Image as ImageIcon, Archive, Code } from "lucide-react";

interface WorkspaceFile {
  name: string;
  size: number;
  modifiedAt: number;
}

interface WorkspaceFilesProps {
  vmid: number;
  idToken: string;
}

function formatBytes(bytes: number, decimals = 1) {
  if (!+bytes) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}

function getFileIcon(filename: string) {
  const ext = filename.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'pdf':
    case 'doc':
    case 'docx':
    case 'txt':
    case 'md':
      return <FileText className="w-5 h-5 text-blue-400" />;
    case 'png':
    case 'jpg':
    case 'jpeg':
    case 'gif':
    case 'svg':
      return <ImageIcon className="w-5 h-5 text-purple-400" />;
    case 'zip':
    case 'tar':
    case 'gz':
      return <Archive className="w-5 h-5 text-yellow-400" />;
    case 'js':
    case 'ts':
    case 'jsx':
    case 'tsx':
    case 'py':
    case 'json':
    case 'html':
    case 'css':
      return <Code className="w-5 h-5 text-green-400" />;
    default:
      return <File className="w-5 h-5 text-gray-400" />;
  }
}

export default function WorkspaceFiles({ vmid, idToken }: WorkspaceFilesProps) {
  const [files, setFiles] = useState<WorkspaceFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchFiles = useCallback(async () => {
    try {
      const res = await fetch(`/api/agent/files?vmid=${vmid}&token=${encodeURIComponent(idToken || '')}`);
      if (!res.ok) throw new Error("Failed to fetch files");
      
      const data = await res.json();
      setFiles(data.files || []);
      setError(null);
    } catch (err: any) {
      setError("Could not load workspace files.");
    } finally {
      setLoading(false);
    }
  }, [vmid, idToken]);

  // Poll every 5 seconds
  useEffect(() => {
    fetchFiles();
    const interval = setInterval(fetchFiles, 5000);
    return () => clearInterval(interval);
  }, [fetchFiles]);

  return (
    <div className="flex flex-col h-full bg-[#0d0d14]">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/[0.04] bg-[#09090b]/50">
        <div className="flex items-center gap-2">
          <File className="w-4 h-4 text-purple-500" />
          <h3 className="text-sm font-medium text-white/90">Workspace Files</h3>
          <span className="px-2 py-0.5 rounded-full bg-white/5 text-[10px] text-white/50 font-mono">/workspace</span>
        </div>
        <button 
          onClick={() => { setLoading(true); fetchFiles(); }}
          className="p-1.5 rounded-md hover:bg-white/10 text-white/50 hover:text-white/90 transition-colors"
          title="Refresh files"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* File List */}
      <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
        {loading && files.length === 0 ? (
          <div className="flex items-center justify-center h-full text-white/30 text-sm gap-2">
            <Loader2 className="w-4 h-4 animate-spin" /> Fetching files...
          </div>
        ) : error ? (
          <div className="flex items-center justify-center h-full text-red-400/80 text-sm">
            {error}
          </div>
        ) : files.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-white/30 space-y-2">
            <Archive className="w-8 h-8 opacity-20" />
            <p className="text-sm">Workspace is empty</p>
            <p className="text-xs opacity-50">Files generated by OpenCode will appear here</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {files.map((file) => (
              <a
                key={file.name}
                href={`/api/agent/download?vmid=${vmid}&path=${encodeURIComponent(file.name)}&token=${encodeURIComponent(idToken)}`}
                download={file.name}
                className="group flex flex-col p-3 rounded-xl bg-white/[0.02] border border-white/[0.05] hover:bg-white/[0.04] hover:border-purple-500/30 transition-all cursor-pointer"
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="p-2 rounded-lg bg-black/40 shadow-inner">
                    {getFileIcon(file.name)}
                  </div>
                  <div className="p-1.5 rounded-md text-white/0 group-hover:text-purple-400 group-hover:bg-purple-500/10 transition-colors">
                    <Download className="w-3.5 h-3.5" />
                  </div>
                </div>
                <div className="mt-1">
                  <p className="text-sm font-medium text-white/90 truncate" title={file.name}>
                    {file.name}
                  </p>
                  <div className="flex items-center justify-between mt-1">
                    <p className="text-xs text-white/40 font-mono">
                      {formatBytes(file.size)}
                    </p>
                  </div>
                </div>
              </a>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
